var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_f358593f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1e1d6738._.js")
R.c("server/chunks/ssr/node_modules_e2d1c5df._.js")
R.c("server/chunks/ssr/[externals]__e8a2741f._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_115f2fd5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_mime-db_f953de6b._.js")
R.c("server/chunks/ssr/node_modules_axios_dist_node_axios_cjs_f5079612._.js")
R.c("server/chunks/ssr/node_modules_@tobyg74_tiktok-api-dl_4f6a7b40._.js")
R.c("server/chunks/ssr/node_modules_cheerio_dist_commonjs_c946ed47._.js")
R.c("server/chunks/ssr/node_modules_5f669eaa._.js")
R.c("server/chunks/ssr/node_modules_parse5_dist_cjs_90ac205d._.js")
R.c("server/chunks/ssr/node_modules_iconv-lite_d5cd4a2b._.js")
R.c("server/chunks/ssr/node_modules_undici_lib_dispatcher_9f4a4607._.js")
R.c("server/chunks/ssr/node_modules_undici_lib_llhttp_f59e41b0._.js")
R.c("server/chunks/ssr/node_modules_undici_lib_web_a141d80e._.js")
R.c("server/chunks/ssr/node_modules_undici_lib_f2a19df5._.js")
R.c("server/chunks/ssr/node_modules_undici_index_0b73a584.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d9b2908._.js")
R.c("server/chunks/ssr/[root-of-the-server]__36d3b58a._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { GLOBAL_ERROR_MODULE => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
